### ISSUE TITLE
Member expiration date should not be last vote but the closing date of last ballot in which the user has voted

### ISSUE THREAD

**Issue by torusJKL** [BitcoinUnlimited/BitcoinUnlimitedVotingWebService#12]
Due to the fact that the ballot is open for multiple days the expiration date of the members can differ based on when during the ballot period the member has voted.

Here 2 members who voted 2 days apart and thus the member who voted earlier would expire earlier.

Norway would expire on Sept 21.
https://www.bitcoinunlimited.info/voting/render/member/570f66ea5d6d7881e180f4c0a94d40c848dac62226917aff09a5e7f9c1759d38

AdrianX would expire on Sept 23.
https://www.bitcoinunlimited.info/voting/render/member/cf4bf428ed6ff9c581fe641c6d05c5efb3d948b0b5958f4d401828bdfe7251bf

The ballot was closed on Sept 24 and that date should be used as the expiration date for all members that have voted during the ballot period.

**Comment by awemany** [comment]
The last action of the member who voted was my understanding on how to interpret the BU articles, specifically this part:

> Member: an individual who is invited (by BUIP) to join the Confederation, signs this document, and has joined or voted within the last 1 year.

How do we clarify/solve this, @AndrewClifford?

**Comment by AndrewClifford** [comment]
My view is that the act of casting a vote is a "keep alive" for membership status, immediately adding 1 year. So,  the actual end of a voting session (ballot) is not a factor.

**Comment by awemany** [comment]
Ok, good. This is how I understand it as well and how it is handled right now and also how it has been handled in the past. 

@torusJKL: I am surprised it is an issue, as "has joined or voted" are pretty simple and clear terms.  If you think this might become an issue down the road, I'd suggest writing a clarifying BUIP on this.
