### ISSUE TITLE
multi action string is shown without new lines and can't be verified

### ISSUE THREAD

**Issue by torusJKL** [BitcoinUnlimited/BitcoinUnlimitedVotingWebService#13]
When using the multi action vote the individual votes are separated by @@@@@ on a dedicated line between the votes.

e.g.
bitcoin-unlimited-voting: 9a68078bbff9de910bb8c377e699832cc907f9ce048625b18b0fe7ea1da14689 cast-member-ballot name bitsko address 1Bitsko32RrVBw4FxBRyM7x1bkbognCFFz by torusJKL answer accept
**@@@@@**
bitcoin-unlimited-voting: 9a68078bbff9de910bb8c377e699832cc907f9ce048625b18b0fe7ea1da14689 cast-member-ballot name singularity address 15GEoJf5GJYAsdXxZCMt1iX4j9HcpvDzkn by torusJKL answer accept

But when the past string is rendered on the homepage for later vierification of the voting then the new line is removed resulting in a different string that fails to verify with the signature of the above string.

e.g.
bitcoin-unlimited-voting: 9a68078bbff9de910bb8c377e699832cc907f9ce048625b18b0fe7ea1da14689 cast-member-ballot name bitsko address 1Bitsko32RrVBw4FxBRyM7x1bkbognCFFz by torusJKL answer accept **@@@@@** bitcoin-unlimited-voting: 9a68078bbff9de910bb8c377e699832cc907f9ce048625b18b0fe7ea1da14689 cast-member-ballot name singularity address 15GEoJf5GJYAsdXxZCMt1iX4j9HcpvDzkn by torusJKL answer accept

**Comment by awemany** [comment]
Good catch. Due to some HTTP form oddity that I haven't quite figured out yet, returns (\r) are inserted before I get the string on my side, so there was trouble on that newline front already. But the newlines should show though do not do that. I'll have a look.

**Comment by awemany** [comment]
Ok, I updated the rendering of the multi_action_string for verification. Does this work for you?

**Comment by torusJKL** [comment]
Yes, it works for me.
Thanks.
